#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"
username=$USER

# a branch name where you want to prevent git push. In this case, it's "master"
#if [ "$branch" = "master" ]; then
#  echo "You can't commit directly to '"${branch}"' branch" 
#  echo "Directly pushing to master is blocked. Instead open a Pull Request and request a merge to master."
#  exit 1 
#fi
