name: CI/CD Pipeline 

on:
   pull_request:
      branches:
         - 'master'
      paths-ignore:
         - '**.md'

jobs:
   run_pipeline:
      name: Run CI/CD Pipeline
      runs-on: ubuntu-latest
      steps:
         - name: Checkout source code
           uses: actions/checkout@v2
   run_python_pipeline:
      uses: ./.github/workflows/.python_pipe.yaml
