name: Create a new Release

on:
   workflow_dispatch:
      inputs:
         preRelease:
            description: 'Pre-release'
            required: true
            default: false
            type: boolean
         draftRelease:
            description: 'Draft a release'
            required: false
            default: false
            type: boolean
         releaseTitle:
            description: 'Release title'
            required: true
            default: 'Release'
            type: string

jobs:
   create_release:
      name: Create a new Release
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v2
           with:
              fetch-depth: 0 # Number of commits to fetch. 0 indicates all history for all branches and tags
         - name: Bump version and push tag
           id: tag_version
           uses: mathieudutour/github-tag-action@v6.0
           with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
         - name: Create Release
           id: create_release
           uses: actions/create-release@latest
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
           with:
              tag_name: ${{ steps.tag_version.outputs.new_tag }}
              release_name: ${{ github.event.inputs.releaseTitle }} ${{ steps.tag_version.outputs.new_tag }}
              body: |
                 ${{ steps.tag_version.outputs.changelog }}
              prerelease: ${{ github.event.inputs.preRelease }}
              draft: ${{ github.event.inputs.draftRelease }}
